apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-app-ingress
  namespace: ticketing-app
  annotations:
    # 1. Tells K8s to use the Nginx controller you just installed
    kubernetes.io/ingress.class: nginx
    
    # 2. Standard optimization (optional but good)
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticketing-app-service
                port:
                  number: 80
