apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-domain-ingress
  namespace: ticketing-app
  annotations:
    # Tells Kubernetes to use the Nginx Controller you installed
    kubernetes.io/ingress.class: "nginx"
    
    # OPTIONAL: Force SSL Redirect (Good since Cloudflare handles the certs)
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: aniljaiswar.pp.ua
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticketing-app-service   # Your App Service Name
                port:
                  number: 80        # Your App Service Port
