apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticket-stats-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack  # MUST match your Prometheus release label
spec:
  selector:
    matchLabels:
      app: ticket-stats-exporter # Matches the label we put on the Deployment
  endpoints:
  - port: metrics # We will define this port name in the Service below
    interval: 30s
    path: /metrics
    honorLabels: true
