apiVersion: v1
kind: Service
metadata:
  name: ticket-stats-exporter
  namespace: monitoring
  labels:
    app: ticket-stats-exporter
    release: prometheus-stack
spec:
  selector:
    app: ticket-stats-exporter
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187

